<?PHP defined('_kexec') or die; ?>
</head>
<body>
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
        <ul class="nav">
            <li class="active">
                <a href="#">Home</a>
            </li>
            <li><a href="#">Link</a></li>
            <li><a href="#">Link</a></li>
        </ul>
    </div>
  </div>
</div>
