<?PHP defined('_kexec') or die; ?>
</head>
<body>
  <!--[if lt IE 7]><p class=chromeframe>Your browser is <em>ancient!</em> <a href="http://browsehappy.com/">Upgrade to a different browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to experience this site.</p><![endif]-->

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
        <a class="brand" href="/">Mom's Kitchen</a>
        
        <ul class="nav pull-right">
            <li><a href="/admin.php">Admin</a></li>
        </ul>
        
        <form class="navbar-search pull-right">
            <input type="text" class="search-query" placeholder="Search">
        </form>
        
        <ul class="nav pull-right">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Categories
                <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">Soups</a></li>
                    <li><a href="#">Salads</a></li>
                    <li><a href="#">Link</a></li>
                </ul>
            </li>
            <li class="divider-vertical"></li>
        </ul>
    </div>
  </div>
</div>
